fix: open connection count
gomodule/redigo pull request #527
Opened 2020-10-15 15:45 UTC by rhnvrm

This commit releases back the connection in the special
case, so that correct count is always maintained.

Closes #520

2020-10-15 21:04 UTC, stevenh requested changes
Thanks for the first time PR, couple of little issues with the test to fix go vet.

2020-10-15 21:04 UTC, stevenh commented on redis/pool_test.go
> +	ctx1, _ := context.WithTimeout(context.Background(), 1*time.Nanosecond)
This leaks a cancel see:
https://travis-ci.org/github/gomodule/redigo/builds/736087424

2020-10-26 09:42 UTC, rhnvrm commented
@stevenh sorry for the delay, have pushed the context cancellation change to resolve the `go vet` issue in the test.

2020-10-26 15:46 UTC, merged

2020-10-26 15:47 UTC, stevenh commented
Thanks @rhnvrm 👍