Implement DialURLContext(...)
gomodule/redigo pull request #574
Opened 2021-09-26 22:02 UTC by cameronelliott

and convert DialURL to call DialURLContext()

2021-09-26 22:07 UTC, cameronelliott commented
Hey @stevenh this is what I was thinking, although maybe there are reasons to pass the 
context as an option, and it certainly would work functionally.

But it might confuse people.

I have never seen a context.Context passed as an option like that, and the Google
official manner is or was:

> At Google, we require that Go programmers pass a Context parameter as the first argument to every function on the call path between incoming and outgoing requests. 
Based upon this article:
https://go.dev/blog/context

And in my experience, the idiomatic Go way is to have a function named xxxContext when
you want to pass a context.Context in.

So, I might miss there is a way to pass a context.Context in if I didn't see
the method in the method signatures in the index, like in the typical Dial*Context method names.

But maybe it makes sense if the Dial method signatures are multiplying too much.

2021-09-26 22:35 UTC, stevenh commented
Feels like we should change all Dialers to use ctx as the first arg in v2.

I believe xxxContent function naming is due to the lack of context support in early go versions + v1 compatibility guarantee, so the original functions must be kept.

Consistency vs other APIs which require ctx as first parameter is good point, it has the benefit that it enforces the design that a consumer should pass a valid context vs making less obvious with an additional functional option.

2021-09-26 22:37 UTC, stevenh requested changes
Thanks for the PR, I agree this is a better approach.

Lets get the docs for older none ctx Dial functions all updated to explicitly call out their wrap nature.

2021-09-26 22:37 UTC, stevenh commented on redis/conn.go
> +	return DialURLContext(ctx, rawurl, options...)
```suggestion
	return DialURLContext(context.Background(), rawurl, options...)
```

2021-09-26 22:37 UTC, stevenh commented on redis/conn.go
>  // scheme (https://www.iana.org/assignments/uri-schemes/prov/redis).
I suggest we update the docs for `DialURL` to
```golang
// DialURL wraps DialURLContext using context.Background.
```

2021-09-28 18:42 UTC, cameronelliott commented
Can you suggest/write the Conventional Commit labels?
I am not familiar with it.

2021-09-28 20:07 UTC, stevenh commented
> Can you suggest/write the Conventional Commit labels? I am not familiar with it.

Sure It's really simple this is a feature so you would have something like this:
> feat: add DialURLContext
>
> Add DialURLContext so that we can consumers have
> control over cancelation and timeout

2021-09-29 17:25 UTC, stevenh requested changes
Thanks for the changes, just missing the suggested doc change for DialURL which makes it clear to the caller its a wrapper.

2021-09-29 17:25 UTC, stevenh commented on redis/conn.go
>  // scheme (https://www.iana.org/assignments/uri-schemes/prov/redis).
Just missing this @cameronelliott

2021-09-30 01:10 UTC, merged

2021-10-02 00:41 UTC, cameronelliott commented
@stevenh Thanks for taking this PR, and your patience while I got it into some type of passable shape.